title: Syngenon description: Historia Familiar.
remote_theme: just-the-docs/just-the-docs
url: https://xabivpla.github.io/syngenon
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
