title: Syngenon
description: Estrabón, Geografía III 3:7.
theme: just-the-docs

url: https://xabivpla.github.io/syngenon

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
